name: ci

on:
  push:
    branches: ['main']

jobs:
  gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: google-github-actions/auth@v2
        id: google-auth
        with:
          project_id: infrastructure-58ca87ae
          workload_identity_provider: 'projects/796604565132/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
      - uses: docker/login-action@v3
        with:
          registry: us.gcr.io
          username: oauth2accesstoken
          password: ${{ steps.google-auth.outputs.access_token }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: us.gcr.io/infrastructure-58ca87ae/gcloud-pubsub-emulator:current,us.gcr.io/infrastructure-58ca87ae/gcloud-pubsub-emulator:latest,us.gcr.io/infrastructure-58ca87ae/gcloud-pubsub-emulator:${{ github.sha }}
